### ISSUE TITLE
Create a Login Feature that uses MySQL Database, Spring Security, and JWT for Authentication

### ISSUE THREAD

**Issue by TshepoMokgoatjane** [TshepoMokgoatjane/tms#64]
Create a Login Feature that uses MySQL Database, Spring Security, and JWT for Authentication.

We are now going to do away with the hardcoded feature.

**Check out the following materials:**

- [x] Section 13 - No hardcoding and MySQL usage
- [x] Section 16 - Offers Spring Security in depth
- [ ] https://www.javaguides.net/2018/10/user-registration-module-using-springboot-springmvc-springsecurity-hibernate5-thymeleaf-mysql.html
- [ ] https://www.javadevjournal.com/spring-security/registration-with-spring-security/#google_vignette

**Tasks to be completed:**

- [x]  Create JPA Entities - User and Role
- [x]  Create UserRepository and RoleRepository
- [x]  Create Service Layer
- [x]  Controller

**Comment by TshepoMokgoatjane** [comment]
This ticket can now be closed. Thanks to Kiro integration and implementation.
